services:
  # API Gateway
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      url-shorten-service:
        condition: service_healthy
    networks:
      - chopurl-network

  # URL Shorten Service
  url-shorten-service:
    build:
      context: ./src/url-shorten-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - REDIS_MASTER=redis-master:6379
      - REDIS_PASSWORD=your_redis_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      etcd:
        condition: service_healthy
      redis-master:
        condition: service_healthy
    networks:
      - chopurl-network
      - redis-network

  # Etcd
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - chopurl-network
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "status"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s # Etcd needs more time to initialize

  # Redis Replication Setup
  redis-master:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-master-data:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis-replica-1:
    image: redis:latest
    command: redis-server --replicaof redis-master 6379
    depends_on:
      redis-master:
        condition: service_healthy
    volumes:
      - redis-replica-1-data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis-replica-2:
    image: redis:latest
    command: ["redis-server", "--replicaof", "redis-master", "6379"]
    depends_on:
      redis-master:
        condition: service_healthy
    volumes:
      - redis-replica-2-data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Redis Sentinel
  redis-sentinel:
    image: redis:latest
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
      echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/sentinel.conf &&
      echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
      echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
      redis-sentinel /etc/sentinel.conf'
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-network

  # Cassandra Seed Node
  cassandra-seed:
    image: cassandra:latest
    container_name: cassandra-seed-1
    volumes:
      - cassandra-seed-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=chopurl-cassandra-cluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - chopurl-network
    ports:
      - "9042:9042"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s # Cassandra needs significant time to initialize

  # Non-seed Cassandra nodes
  cassandra-node:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=chopurl-cassandra-cluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - chopurl-network
    depends_on:
      cassandra-seed:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s # Also needs significant startup time

  cassandra-init:
    image: cassandra:latest
    depends_on:
      cassandra-node:
        condition: service_healthy
    volumes:
      - ./configs/cassandra/:/configs/cassandra/
    command: cqlsh cassandra-seed -f /configs/cassandra/init.cql
    networks:
      - chopurl-network

networks:
  chopurl-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  cassandra-seed-data:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:
